[project]
site_name = "Tremeschin"
site_description = "Projects, blog, funsies, and more."
site_url  = "https://tremeschin.com/"
repo_url  = "https://github.com/Tremeschin/"
copyright = "&copy; CC BY-SA 4.0, <a href='https://github.com/Tremeschin/'>Tremeschin</a> 🇧🇷"
docs_dir  = "website"
nav = [
  {Home = [
    "index.md",
    "about/contributing.md",
    "about/security.md",
    "about/resume.md",
    "about/support.md",
  ]},
  {Projects = [
    "projects/index.md",
    "projects/apps.md",
    "projects/libs.md",
    "projects/feeds.md",
  ]},
]

[project.theme]
name = "zentheme"

[project.theme.icon]
logo = "octicons/package-16"
admonition.bug = "octicons/heart-fill-16" # Fixme

[[project.extra.social]]
name = "GitHub"
icon = "fontawesome/brands/github"
link = "https://github.com/Tremeschin"

[[project.extra.social]]
name = "YouTube"
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/@Tremeschin"

[[project.extra.social]]
name = "Discord"
icon = "fontawesome/brands/discord"
link = "https://discord.gg/KjqvcYwRHm"

[[project.extra.social]]
name = "Patreon"
icon = "fontawesome/brands/patreon"
link = "https://www.patreon.com/Tremeschin"

[[project.extra.social]]
name = "GitHub Sponsors"
icon = "simple/githubsponsors"
link = "https://github.com/sponsors/Tremeschin/"
