name: make-website
on:
  workflow_dispatch:
  push:
    paths:
      - "website/**"

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uvx zensical build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

      - name: Deploy pages
        uses: actions/deploy-pages@v4
